name: media_kit_video_controls
description: UI video controls for package:media_kit. Pre-built & customizable.
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 1.0.0
funding:
  - https://www.github.com/sponsors/alexmercerind

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  synchronized: ^3.1.0
  screen_brightness: ^0.2.2
  volume_controller: ^2.0.7
  # NOTE: Bump before publishing to pub.dev
  media_kit_video: ^0.0.12

# NOTE: Remove before publishing to pub.dev
dependency_overrides:
  media_kit:
    path: ../media_kit
  media_kit_video:
    path: ../media_kit_video

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
