name: flutter_meedu_videoplayer_example
description: Demonstrates how to use the flutter_meedu_videoplayer plugin.

publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.0
  video_player_media_kit:
    path: ../
  file_picker: ^5.2.4
  visibility_detector: ^0.3.3
  media_kit_libs_ios_video: ^1.1.1
  media_kit_libs_android_video: ^1.3.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
    - assets/Butterfly-209.mp4
    - assets/Butterfly-209.webm
    - assets/bumble_bee_captions.srt
    - assets/bumble_bee_captions.vtt
    - assets/Audio.mp3
