name: video_player_media_kit
description: package:video_player support for all platforms. Based on package:media_kit.
homepage: https://github.com/media-kit/media-kit
repository: https://github.com/media-kit/media-kit
version: 1.0.0
topics:
  - video
  - video-player
  - cross-platform
  - media-kit

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.6
  media_kit_video: ^1.1.7
  video_player_platform_interface: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  media_kit:
    path: ../media_kit
  media_kit_video:
    path: ../media_kit_video
