name: Github Actions
on: [push, pull_request]

defaults:
  run:
    working-directory: media_kit_test

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build windows --verbose
      - run: cmake -E tar "cfv" "media_kit_test_win32_x64.7z" --format=7zip "build\windows\runner\Release"
      - uses: actions/upload-artifact@v1
        with:
          name: media_kit_test_win32_x64
          path: media_kit_test/media_kit_test_win32_x64.7z
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          tag_name: "vnext"
          files: |
            media_kit_test/media_kit_test_win32_x64.7z
          token: ${{ secrets.ACCESS_TOKEN }}

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - run: sudo apt-get update
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev p7zip-full p7zip-rar
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build linux --verbose
      - run: 7z a media_kit_test_linux_x64.7z build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v1
        with:
          name: media_kit_test_linux_x64
          path: media_kit_test/media_kit_test_linux_x64.7z
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          tag_name: "vnext"
          files: |
            media_kit_test/media_kit_test_linux_x64.7z
          token: ${{ secrets.ACCESS_TOKEN }}
